name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: debian-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 192.168.100.100
          username: Noomvv
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/var
            git pull origin main
            npm install
            npm run build
            pm2 restart my-drive-app